# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Windows and Linux
      run: |
        make build.win
        make build.linux
    
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      # skip if pull request
      if : github.event_name != 'pull_request'
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        tag_name: ${{ github.ref_name }}
        body: |
          Build for commit ${{ github.sha }}
          app files binaries for linux and windows
        files: |
            dist/**
